"""ADR-0184 (Autostart) drift guard: two independent Windows restart-loop
implementations exist by necessity —

- `operator/bridges/shared/corvin-supervisor.ps1` (dev-checkout path, used by
  `bridge.ps1 install-autostart`)
- the heredoc-generated supervisor inside `install.ps1`'s
  `Install-CorvinAutostart` (the pip/uv-tool standalone path, which must stay
  self-contained since it runs via `irm | iex` before any repo checkout
  necessarily exists on disk — see the comment above that function)

They can't be merged into one file without adding a network dependency to the
installer, so instead this test pins them to the SAME bounded-restart shape
(ADR-0184 Stufe-1: 5 restarts per 300s window, then stop) so a future edit to
one doesn't silently leave the other with an unbounded crash loop — the exact
drift class `tests/test_uninstall_windows_autostart.py` already documents for
the autostart *registration* side of these same two files.
"""
from __future__ import annotations

import re
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
_SUPERVISOR = _REPO / "operator" / "bridges" / "shared" / "corvin-supervisor.ps1"
_INSTALL_PS1 = _REPO / "install.ps1"
_BRIDGE_PS1 = _REPO / "operator" / "bridges" / "bridge.ps1"


def _generated_supervisor_block() -> str:
    """Extract the heredoc body install.ps1 writes out as its own
    corvin-supervisor.ps1, with the backtick-escapes install.ps1 needs (to
    keep the text literal inside ITS OWN here-string) stripped back out —
    this normalizes it to look like what actually lands on disk at install
    time, so it's directly comparable to the checked-in dev-checkout file."""
    src = _INSTALL_PS1.read_text(encoding="utf-8")
    start = src.index('@"\n# Auto-generated by install.ps1')
    end = src.index('"@ | Set-Content', start)
    block = src[start:end]
    return block.replace("`$", "$")


class TestBoundedRestartParity:
    def test_both_files_use_the_same_restart_cap_and_window(self) -> None:
        supervisor_src = _SUPERVISOR.read_text(encoding="utf-8")
        generated_src = _generated_supervisor_block()

        for label, src in (("corvin-supervisor.ps1", supervisor_src),
                            ("install.ps1 generated block", generated_src)):
            assert re.search(r"MaxRestarts\s*=\s*5\b", src), (
                f"{label}: expected MaxRestarts=5 (ADR-0184 Stufe-1 cap)"
            )
            assert re.search(r"RestartWindowSec\s*=\s*300\b", src), (
                f"{label}: expected RestartWindowSec=300 (ADR-0184 Stufe-1 window)"
            )

    def test_both_files_have_a_rolling_window_filter_before_the_cap_check(self) -> None:
        """Guards against someone re-adding a naive `while($true){...; sleep 5}`
        with no cap at all — the Where-Object rolling-window filter must run
        before the Count-vs-MaxRestarts comparison in both files."""
        for label, src in (
            ("corvin-supervisor.ps1", _SUPERVISOR.read_text(encoding="utf-8")),
            ("install.ps1 generated block", _generated_supervisor_block()),
        ):
            where_idx = src.find("Where-Object")
            cap_idx = src.find("Count -ge")
            assert where_idx != -1, f"{label}: missing rolling-window filter"
            assert cap_idx != -1, f"{label}: missing restart-cap check"
            assert where_idx < cap_idx, (
                f"{label}: rolling-window filter must run BEFORE the cap check"
            )

    def test_both_files_stop_instead_of_looping_forever_once_capped(self) -> None:
        for label, src in (
            ("corvin-supervisor.ps1", _SUPERVISOR.read_text(encoding="utf-8")),
            ("install.ps1 generated block", _generated_supervisor_block()),
        ):
            cap_idx = src.find("Count -ge")
            assert cap_idx != -1, f"{label}: missing restart-cap check"
            # `break` must appear shortly after the cap check fires — i.e. the
            # loop actually stops instead of merely logging and continuing.
            window = src[cap_idx:cap_idx + 400]
            assert "break" in window, (
                f"{label}: restart cap is checked but the loop doesn't `break`"
            )


class TestScheduledTaskSettingsParity:
    """The Scheduled-Task registration itself (Trigger/Settings/RunLevel) is
    a second, independent copy in bridge.ps1 (dev-checkout) vs install.ps1
    (standalone) — same drift risk as the supervisor loop above. Pin the
    settings that matter for "survives crash/reboot" so they can't quietly
    diverge (e.g. one script losing -RestartCount or switching RunLevel)."""

    def test_both_use_atlogon_trigger(self) -> None:
        for label, path in (("bridge.ps1", _BRIDGE_PS1), ("install.ps1", _INSTALL_PS1)):
            src = path.read_text(encoding="utf-8")
            assert "New-ScheduledTaskTrigger -AtLogOn" in src, (
                f"{label}: expected the Stufe-1 -AtLogOn trigger"
            )

    def test_both_use_the_same_settings_set_flags(self) -> None:
        expected = [
            "-Hidden",
            "-AllowStartIfOnBatteries",
            "-DontStopIfGoingOnBatteries",
            "-ExecutionTimeLimit ([TimeSpan]::Zero)",
            "-RestartCount 999",
            "-RestartInterval (New-TimeSpan -Minutes 1)",
            "-MultipleInstances IgnoreNew",
        ]
        for label, path in (("bridge.ps1", _BRIDGE_PS1), ("install.ps1", _INSTALL_PS1)):
            src = path.read_text(encoding="utf-8")
            for flag in expected:
                assert flag in src, f"{label}: missing/changed ScheduledTaskSettingsSet flag {flag!r}"

    def test_both_register_with_limited_run_level(self) -> None:
        """RunLevel Limited (not Highest) is the whole point of Stufe 1 — no
        elevation. A silent switch to -RunLevel Highest here would turn the
        default, no-consent path into an elevated one (ADR-0184 Decision 3)."""
        for label, path in (("bridge.ps1", _BRIDGE_PS1), ("install.ps1", _INSTALL_PS1)):
            src = path.read_text(encoding="utf-8")
            assert "-RunLevel Limited" in src, f"{label}: expected -RunLevel Limited"
            assert "-RunLevel Highest" not in src, (
                f"{label}: found -RunLevel Highest — Stufe 1 must never require elevation"
            )


class TestNoClosableWindow:
    """Regression for a real bug: install.ps1's Install-CorvinAutostart falls
    back to a bare `Start-Process corvinos-serve` if Scheduled-Task
    registration throws for any reason. That fallback used to pass
    `-WindowStyle Minimized` — which still creates a taskbar entry the user
    can click and close, silently killing the "background" process exactly
    the way a visible console window would. Every process this installer
    starts must be `-WindowStyle Hidden` (no window at all) or run via a
    Scheduled Task with `-Hidden` — never Minimized/Normal/Maximized, which
    all leave something on screen for a user to close."""

    _NOT_ALLOWED = re.compile(r"-WindowStyle\s+(Minimized|Normal|Maximized)\b")

    def test_no_closable_windowstyle_anywhere(self) -> None:
        for label, path in (("install.ps1", _INSTALL_PS1), ("bridge.ps1", _BRIDGE_PS1)):
            src = path.read_text(encoding="utf-8")
            match = self._NOT_ALLOWED.search(src)
            assert not match, (
                f"{label}: found {match.group(0) if match else ''} — must be "
                "-WindowStyle Hidden, not a style that leaves a closable window"
            )

    def test_install_ps1_fallback_start_uses_hidden(self) -> None:
        src = _INSTALL_PS1.read_text(encoding="utf-8")
        fallback_idx = src.index("Could not set up auto-restart")
        window = src[fallback_idx:fallback_idx + 600]
        assert "corvinos-serve" in window, "fallback Start-Process call not found where expected"
        assert "-WindowStyle Hidden" in window, (
            "install.ps1's no-autostart fallback must launch corvinos-serve with "
            "-WindowStyle Hidden, not a visible/minimized window"
        )


if __name__ == "__main__":
    import sys

    t = TestBoundedRestartParity()
    t.test_both_files_use_the_same_restart_cap_and_window()
    t.test_both_files_have_a_rolling_window_filter_before_the_cap_check()
    t.test_both_files_stop_instead_of_looping_forever_once_capped()
    t2 = TestScheduledTaskSettingsParity()
    t2.test_both_use_atlogon_trigger()
    t2.test_both_use_the_same_settings_set_flags()
    t2.test_both_register_with_limited_run_level()
    t3 = TestNoClosableWindow()
    t3.test_no_closable_windowstyle_anywhere()
    t3.test_install_ps1_fallback_start_uses_hidden()
    print("all tests passed")
    sys.exit(0)
