"""gRPC server for the Gateway — real implementation.

ADR-0007 Phase 7.3 follow-up. The Phase 7.3 commit shipped the
proto + a NotImplementedError skeleton because grpcio wasn't a
declared runtime dep. This module now wires the generated stubs
to the same business logic as the REST surface:

  * SubmitRun    → RunRequest + RunRegistry.create + dispatcher
  * GetRun       → RunRegistry.get
  * StreamEvents → RunEventBuffer.subscribe

grpcio is still NOT in the default Dockerfile / Helm chart — the
gRPC surface is opt-in for operators who set ``GATEWAY_GRPC_PORT``
in their environment. The REST surface stays authoritative.

Auth model
----------

gRPC clients send a JWT bearer token via the ``authorization``
metadata header (``Bearer <jwt>``). For local deployments no
authorization header is required — the loopback binding is the
security boundary.
"""
from __future__ import annotations

import threading
import time
from concurrent import futures
from typing import Any, Iterator

from google.protobuf import json_format, timestamp_pb2

from ..auth import ResolvedToken
from ..dispatcher import RunDispatcher
from ..oidc import looks_like_jwt, resolve_jwt
from ..runs import (
    RunNotFound,
    RunRecord,
    RunRegistry,
    RunRequest,
    RunStoreMalformed,
    TERMINAL_STATES,
)
from ..rate_limit import RateLimiter, audit_rate_limited


class GrpcUnavailable(RuntimeError):
    """Raised when grpcio is not installed but the server is asked
    to bind a port. Kept for backwards-compat with the Phase 7.3
    skeleton; modern installs have grpcio."""


# Lazy import so this module stays import-safe without grpcio.
def _import_grpc() -> Any:
    try:
        import grpc
        return grpc
    except ImportError as exc:
        raise GrpcUnavailable(
            "grpcio not installed; "
            "pip install grpcio grpcio-tools"
        ) from exc


def _import_stubs() -> tuple[Any, Any]:
    """Return ``(corvin_pb2, corvin_pb2_grpc)``. Generated by
    ``python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. corvin.proto``."""
    try:
        from . import corvin_pb2, corvin_pb2_grpc  # type: ignore[import]
        return corvin_pb2, corvin_pb2_grpc
    except ImportError as exc:
        raise GrpcUnavailable(
            "corvin_pb2 stubs not generated; run "
            "`python -m grpc_tools.protoc -I . --python_out=. "
            "--grpc_python_out=. corvin.proto` "
            "from core/gateway/corvin_gateway/grpc/"
        ) from exc


# ── Helpers ─────────────────────────────────────────────────────────


def _extract_bearer(context: Any) -> str | None:
    """Pull ``authorization: Bearer …`` from the gRPC metadata."""
    md = dict(context.invocation_metadata())
    val = md.get("authorization", "")
    if not isinstance(val, str) or not val.lower().startswith("bearer "):
        return None
    presented = val[7:].strip()
    return presented or None


def _authenticate(context: Any) -> ResolvedToken | None:
    presented = _extract_bearer(context)
    if presented is None or not looks_like_jwt(presented):
        return None
    return resolve_jwt(presented)


def _ts_proto(epoch: float) -> Any:
    """epoch seconds → google.protobuf.Timestamp"""
    ts = timestamp_pb2.Timestamp()
    ts.FromSeconds(int(epoch))
    return ts


def _record_to_proto(record: RunRecord, pb: Any) -> Any:
    proto = pb.RunRecord()
    proto.run_id = record.run_id
    proto.tenant_id = record.tenant_id
    proto.status = record.status
    proto.created_at.CopyFrom(_ts_proto(record.created_at))
    proto.updated_at.CopyFrom(_ts_proto(record.updated_at))
    if record.request:
        json_format.ParseDict(record.request, proto.request)
    if record.result:
        json_format.ParseDict(record.result, proto.result)
    if record.error:
        proto.error = record.error
    return proto


# ── Servicer ────────────────────────────────────────────────────────


class CorvinGatewayServicer:
    """Real implementation of the gRPC service. Methods abort with
    gRPC's StatusCode on auth / authz / not-found failures."""

    def __init__(
        self,
        *,
        dispatcher: RunDispatcher | None = None,
        rate_limiter: RateLimiter | None = None,
    ) -> None:
        self._dispatcher = dispatcher or RunDispatcher()
        self._rate_limiter = rate_limiter or RateLimiter()

    # ---- SubmitRun -----------------------------------------------

    def SubmitRun(self, request: Any, context: Any) -> Any:
        grpc = _import_grpc()
        pb, _ = _import_stubs()
        token = _authenticate(context)
        if token is None:
            context.abort(
                grpc.StatusCode.UNAUTHENTICATED, "invalid bearer token"
            )
        if request.tenant_id != token.tenant_id:
            context.abort(
                grpc.StatusCode.PERMISSION_DENIED,
                f"cross-tenant: url={request.tenant_id!r} "
                f"token={token.tenant_id!r}",
            )
        # Rate-limit gate (Phase 7.2)
        allowed, bucket = self._rate_limiter.check(request.tenant_id)
        if not allowed:
            if bucket is not None:
                audit_rate_limited(
                    request.tenant_id,
                    capacity=bucket.capacity,
                    tokens_remaining=bucket.tokens,
                )
            context.abort(
                grpc.StatusCode.RESOURCE_EXHAUSTED, "rate-limited"
            )

        # Project proto Run → AWP RunRequest dict
        run = request.run
        spec_pb = run.spec
        spec_dict: dict[str, Any] = {
            "persona": spec_pb.persona,
            "input":   spec_pb.input,
        }
        if spec_pb.HasField("webhook"):
            spec_dict["webhook"] = {
                "url":         spec_pb.webhook.url,
                "secret_ref":  spec_pb.webhook.secret_ref,
            }
        if spec_pb.HasField("budget_override"):
            bo: dict[str, Any] = {}
            if spec_pb.budget_override.max_wall_clock_s:
                bo["max_wall_clock_s"] = spec_pb.budget_override.max_wall_clock_s
            if spec_pb.budget_override.max_tokens:
                bo["max_tokens"] = spec_pb.budget_override.max_tokens
            if bo:
                spec_dict["budget_override"] = bo
        body = {
            "apiVersion": "corvin/v1",
            "kind":       "Run",
            "spec":       spec_dict,
        }
        try:
            run_request = RunRequest.model_validate(body)
        except Exception as exc:
            context.abort(
                grpc.StatusCode.INVALID_ARGUMENT,
                f"invalid run spec: {exc}",
            )
        registry = RunRegistry()
        try:
            record = registry.create(request.tenant_id, run_request)
        except RunStoreMalformed as exc:
            context.abort(
                grpc.StatusCode.INTERNAL,
                f"tenant-not-provisioned: {exc}",
            )
        # Submit MUST run inside an asyncio loop. gRPC servers run
        # method handlers on a threadpool; we route the submit
        # through the dispatcher's loop via a thread-safe future.
        loop = getattr(self._dispatcher, "_loop", None)
        if loop is not None and loop.is_running():
            import asyncio
            asyncio.run_coroutine_threadsafe(
                self._dispatch_async(request.tenant_id, record.run_id),
                loop,
            )
        return pb.SubmitRunResponse(run_id=record.run_id, status=record.status)

    async def _dispatch_async(self, tid: str, run_id: str) -> None:
        self._dispatcher.submit(tid, run_id)

    # ---- GetRun --------------------------------------------------

    def GetRun(self, request: Any, context: Any) -> Any:
        grpc = _import_grpc()
        pb, _ = _import_stubs()
        token = _authenticate(context)
        if token is None:
            context.abort(grpc.StatusCode.UNAUTHENTICATED, "invalid bearer token")
        if request.tenant_id != token.tenant_id:
            context.abort(grpc.StatusCode.PERMISSION_DENIED, "cross-tenant")
        registry = RunRegistry()
        try:
            record = registry.get(request.tenant_id, request.run_id)
        except RunNotFound:
            context.abort(grpc.StatusCode.NOT_FOUND, "run not found")
        except RunStoreMalformed as exc:
            context.abort(
                grpc.StatusCode.INTERNAL, f"run-store-malformed: {exc}",
            )
        return _record_to_proto(record, pb)

    # ---- StreamEvents --------------------------------------------

    def StreamEvents(self, request: Any, context: Any) -> Iterator[Any]:
        grpc = _import_grpc()
        pb, _ = _import_stubs()
        token = _authenticate(context)
        if token is None:
            context.abort(grpc.StatusCode.UNAUTHENTICATED, "invalid bearer token")
        if request.tenant_id != token.tenant_id:
            context.abort(grpc.StatusCode.PERMISSION_DENIED, "cross-tenant")
        registry = RunRegistry()
        try:
            registry.get(request.tenant_id, request.run_id)
        except RunNotFound:
            context.abort(grpc.StatusCode.NOT_FOUND, "run not found")
        except RunStoreMalformed:
            context.abort(grpc.StatusCode.INTERNAL, "run-store-malformed")

        # Live tap via the dispatcher's event registry. If no buffer
        # is around (process restart), fall through to a one-shot
        # terminal snapshot like the REST SSE endpoint does.
        buf = self._dispatcher.events.get(
            request.tenant_id, request.run_id,
        )
        if buf is None:
            try:
                fresh = registry.get(request.tenant_id, request.run_id)
            except (RunNotFound, RunStoreMalformed):
                return
            event_type = (
                f"run.{fresh.status}"
                if fresh.status in TERMINAL_STATES
                else "run.snapshot"
            )
            ev = pb.StreamEvent()
            ev.event_type = event_type
            ev.text = ""
            ev.error = fresh.error or ""
            ev.ts.CopyFrom(_ts_proto(fresh.updated_at))
            yield ev
            return

        # We can't run `async for` from a sync servicer; consume the
        # buffer via a thread-safe queue.
        import queue as _queue
        q: _queue.Queue = _queue.Queue()
        STOP = object()

        loop = getattr(self._dispatcher, "_loop", None)

        async def _pump() -> None:
            try:
                async for event in buf.subscribe():
                    q.put(event)
            finally:
                q.put(STOP)

        if loop is not None and loop.is_running():
            import asyncio
            asyncio.run_coroutine_threadsafe(_pump(), loop)
        else:
            # Best-effort: subscribe blocks if no loop; signal stop.
            q.put(STOP)

        while True:
            try:
                item = q.get(timeout=30.0)
            except _queue.Empty:
                break
            if item is STOP:
                break
            ev = pb.StreamEvent()
            ev.event_type = str(item.get("type", ""))
            ev.text = str(item.get("text", "") or "")
            usage = item.get("usage") or {}
            if usage:
                json_format.ParseDict(usage, ev.usage)
            err = item.get("error")
            if err:
                ev.error = str(err)
            ev.ts.CopyFrom(_ts_proto(time.time()))
            yield ev


# ── Server bootstrap ────────────────────────────────────────────────


def start_server(
    *,
    host: str = "0.0.0.0",
    port: int = 50051,
    dispatcher: RunDispatcher | None = None,
    rate_limiter: RateLimiter | None = None,
    max_workers: int = 8,
) -> Any:
    """Bind a gRPC server on (host, port). Returns the server handle.

    The caller is responsible for ``server.wait_for_termination()``
    or ``server.stop(grace)``.
    """
    grpc = _import_grpc()
    pb, pb_grpc = _import_stubs()
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=max_workers))
    pb_grpc.add_CorvinGatewayServicer_to_server(
        CorvinGatewayServicer(
            dispatcher=dispatcher,
            rate_limiter=rate_limiter,
        ),
        server,
    )
    server.add_insecure_port(f"{host}:{port}")
    server.start()
    return server
