apiVersion: v1
kind: Service
metadata:
  name: {{ include "corvin-gateway.fullname" . }}
  labels:
    {{- include "corvin-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "corvin-gateway.selectorLabels" . | nindent 4 }}
