"""Run-state checkpoint/resume (ADR-0188 M5).

One JSON file per paused run under
`<corvin_home>/tenants/<tid>/workflow_runs/<run_id>.json` — same append-only,
run-id-keyed pattern as the rest of the runtime's per-run artifact stores
(no new storage subsystem). A checkpoint is written only when a run pauses
(`ask_human`/`answer` under `orchestration.engine: chat`) and deleted once
the run reaches a terminal state (complete/failed) after resuming.
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parents[3]


def _paths_module():
    if str(_REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(_REPO_ROOT))
    import corvinOS.shared.paths as paths  # type: ignore

    return paths


def _runs_dir(tenant_id: str | None) -> Path:
    d = _paths_module().tenant_workflow_runs_dir(tenant_id)
    d.mkdir(parents=True, exist_ok=True)
    return d


def _run_path(run_id: str, tenant_id: str | None) -> Path:
    # run_id is generated by this module (secrets.token_hex) — never
    # user-controlled path input, but validate defensively anyway.
    if not run_id or any(c in run_id for c in ("/", "\\", "..")):
        raise ValueError(f"invalid run_id: {run_id!r}")
    return _runs_dir(tenant_id) / f"{run_id}.json"


def save(
    run_id: str,
    *,
    workflow_path: str,
    workflow_name: str,
    inputs: dict[str, Any],
    state: dict[str, Any],
    completed_ids: list[str],
    skipped_ids: list[str] | None = None,
    paused_at_node: str,
    prompt: str,
    channel: str | None,
    chat_id: str | None,
    expect: dict[str, Any] | None,
    tenant_id: str | None = None,
) -> Path:
    payload = {
        "run_id": run_id,
        "workflow_path": workflow_path,
        "workflow_name": workflow_name,
        "inputs": inputs,
        "state": state,
        "completed_ids": completed_ids,
        "skipped_ids": skipped_ids or [],
        "paused_at_node": paused_at_node,
        "prompt": prompt,
        "channel": channel,
        "chat_id": chat_id,
        "expect": expect,
        "status": "paused",
        "paused_at_ms": int(time.time() * 1000),
    }
    p = _run_path(run_id, tenant_id)
    p.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return p


def load(run_id: str, *, tenant_id: str | None = None) -> dict[str, Any] | None:
    p = _run_path(run_id, tenant_id)
    if not p.exists():
        return None
    return json.loads(p.read_text(encoding="utf-8"))


def delete(run_id: str, *, tenant_id: str | None = None) -> None:
    p = _run_path(run_id, tenant_id)
    p.unlink(missing_ok=True)


def list_paused(*, tenant_id: str | None = None) -> list[dict[str, Any]]:
    d = _runs_dir(tenant_id)
    out = []
    for f in sorted(d.glob("*.json")):
        try:
            out.append(json.loads(f.read_text(encoding="utf-8")))
        except (json.JSONDecodeError, OSError):
            continue
    return out
